
package br.com.gtmf.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimInterfaceImplService", targetNamespace = "http://gtmf.com.br/", wsdlLocation = "http://localhost:8080/ws/sim?wsdl")
public class SimInterfaceImplService
    extends Service
{

    private final static URL SIMINTERFACEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMINTERFACEIMPLSERVICE_EXCEPTION;
    private final static QName SIMINTERFACEIMPLSERVICE_QNAME = new QName("http://gtmf.com.br/", "SimInterfaceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/sim?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMINTERFACEIMPLSERVICE_WSDL_LOCATION = url;
        SIMINTERFACEIMPLSERVICE_EXCEPTION = e;
    }

    public SimInterfaceImplService() {
        super(__getWsdlLocation(), SIMINTERFACEIMPLSERVICE_QNAME);
    }

    public SimInterfaceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMINTERFACEIMPLSERVICE_QNAME, features);
    }

    public SimInterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, SIMINTERFACEIMPLSERVICE_QNAME);
    }

    public SimInterfaceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMINTERFACEIMPLSERVICE_QNAME, features);
    }

    public SimInterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimInterfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimInterfaceImpl
     */
    @WebEndpoint(name = "SimInterfaceImplPort")
    public SimInterfaceImpl getSimInterfaceImplPort() {
        return super.getPort(new QName("http://gtmf.com.br/", "SimInterfaceImplPort"), SimInterfaceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimInterfaceImpl
     */
    @WebEndpoint(name = "SimInterfaceImplPort")
    public SimInterfaceImpl getSimInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gtmf.com.br/", "SimInterfaceImplPort"), SimInterfaceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMINTERFACEIMPLSERVICE_EXCEPTION!= null) {
            throw SIMINTERFACEIMPLSERVICE_EXCEPTION;
        }
        return SIMINTERFACEIMPLSERVICE_WSDL_LOCATION;
    }

}
